### ISSUE TITLE
Cost?

### ISSUE THREAD

**Issue by bootstraponline** [blackboard/lambda-selenium#25]
Is there any rough estimate of what this `lambda-selenium` approach costs on a production workload? I'm wondering if reserved instances would be significantly less expensive.

**Comment by tsu-denim** [comment]
If you compare raw compute time used, i.e. 1hr of billed Lambda compute time at max settings vs ec2, they are pretty close to each other. However in my situation, it reduces build times immensely since we can run hundreds of concurrent tests, so there are some compute savings due to our infrastructure setup. What gets interesting is for team productivity, which is harder to quantify. In terms of Selenium/Chrome, it has better stability since we only use the function for a test run and  thrown it away after, cutting down on all the mystery errors you get reusing grid nodes. If you are going to run a large ec2 based selenium grid, I highly recommend https://github.com/groupon/Selenium-Grid-Extras.

**Comment by bootstraponline** [comment]
Selenium-Grid-Extras is unfortunately unmaintained. I had been looking at https://github.com/zalando/zalenium possibly comboed with https://aws.amazon.com/blogs/aws/aws-fargate/

`lambda-selenium` is interesting though. I'll probably try it out in the future.

**Comment by tsu-denim** [comment]
Yeah, it seems so. It was nice while it lasted. Fargate looks really promising. We'll be posting some better examples soon with the full version of Chrome/Firefox now that we have some of their issues with Lambda ironed out.
