### ISSUE TITLE
Help Request for 'Lambda-Selenium: Java Tutorial' 

### ISSUE THREAD

**Issue by 1v1a3x** [blackboard/lambda-selenium#41]
Hello guys, 

Sorry for dummy question.
I've been trying to follow the https://blackboard.github.io/lambda-selenium/java-tutorial.html
instruction in an attempt to accomplish a 'happy path' on the tutorial, but unfortunately got 
errors during commands executions:
> gradle clean unzipLibs shadowJar deploy
> gradle clean test

The error:
`com.amazonaws.services.lambda.model.ResourceNotFoundException: Function not found: arn:aws:lambda:us-east-1:863748774790:function:lambda-selenium-function (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 2f39ee30-f3f6-11e8-ba36-9d649c5bb1c1)`

Could you please help me to figure out what I'm doing wrong?
> aws configure list (Shows that I have a correct AWS profile configuration)

Thank you.

**Comment by wesmcouch** [comment]
Hello, can you post the output from this command? I am guessing there is an error is being thrown.
```
gradle clean unzipLibs shadowJar deploy
```

Can you also verify the cloudformation stack has been deployed in the AWS console?

**Comment by 1v1a3x** [comment]
Hello Wesley,
It's the output of the command:
$ gradle clean unzipLibs shadowJar deploy                              

```FAILURE: Build failed with an exception.```

```
* What went wrong:
Method com/github/jengelman/gradle/plugins/shadow/internal/DependencyFileCollection.getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; is abstract

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

> Can you also verify the cloudformation stack has been deployed in the AWS console?

Sorry, looks like I totally missed the step related to CF Stack deployment.
Is there any other documentation that I can refer to?
Thank you.

**Comment by rahul22022** [comment]
Hello,
I am not sure if this is related but i am running into similar issue where when i run  Gradle clean zipLibs , It runs successfully but when i use --info it actually skips the step.

Task :processResources NO-SOURCE
Skipping task ':processResources' as it has no source files and no previous output files.
:processResources (Thread[Execution worker for ':',5,main]) completed. Took 0.018 secs.
:zipLibs (Thread[Execution worker for ':',5,main]) started.
> Task :zipLibs NO-SOURCE
Skipping task ':zipLibs' as it has no source files and no previous output files.
:zipLibs (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.

Here is my code
task zipLibs(type: Zip) {
    from processResources
    archiveName 'lib.zip'
    destinationDir(file('../bin/'))
}

I am assuming this needs to be run before the unzipLibs task. (OfCorse unzipLibs fail because it can't find any zip file in bin directory.). 

Thanks In Advance for your help.

**Comment by viswanath-2767** [comment]
Hi
I faced a similar issue.  
Downgrading gradle version from 5.5.1 to 4.10.3 resolved the issue

**Comment by rahul22022** [comment]
Thanks Viswanath, It resolved my issue.

Regards,
Rahul

**Comment by 1v1a3x** [comment]
Thanks, Viswanath. My issue was also successfully resolved.
